services:
  web: &web
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - jobportal-network
    command: /start.sh
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.22-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - jobportal-network
  
  proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    networks:
      - jobportal-network
    depends_on:
      - web
  
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - jobportal-network
  
  celeryworker:
    <<: *web
    command: /start-celeryworker.sh
   
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9002:9000"
    env_file:
      - .env
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://${SONAR_HOST}:${SONAR_PORT}/${SONAR_DB}
      - SONAR_JDBC_USERNAME=${SONAR_USER}
      - SONAR_JDBC_PASSWORD=${SONAR_PASSWORD}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - jobportal-network
    depends_on:
      - sonar_db
  
  sonar_db:
    image: postgres:13.22-alpine
    container_name: sonar_db
    environment:
      POSTGRES_USER: ${SONAR_USER}
      POSTGRES_PASSWORD: ${SONAR_PASSWORD}
      POSTGRES_DB: ${SONAR_DB}
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - jobportal-network

  flower:
    <<: *web
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/var/lib/flower
    command: /start-flower.sh

networks:
  jobportal-network:
    external: true

volumes:
  static_data:
  media_data:
  postgres_data:
  redis_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  flower_data:
  

      



